name: wf

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Target environment'
        required: true
  pull_request:
    branches: [main]
    types:
      - closed

jobs:
  wf:
    if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'dev' }}
    steps:
      - name: print
        run: echo '${{ vars.ENVIRONMENT }}'
